#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwitchDeviceStatus.DataLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SolarWindsOrion")]
	public partial class SolarWindsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSysLog(SysLog instance);
    partial void UpdateSysLog(SysLog instance);
    partial void DeleteSysLog(SysLog instance);
    partial void InsertErrorCount(ErrorCount instance);
    partial void UpdateErrorCount(ErrorCount instance);
    partial void DeleteErrorCount(ErrorCount instance);
    #endregion
		
		public SolarWindsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SolarWindsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SolarWindsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SolarWindsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SysLog> SysLogs
		{
			get
			{
				return this.GetTable<SysLog>();
			}
		}
		
		public System.Data.Linq.Table<ErrorCount> ErrorCounts
		{
			get
			{
				return this.GetTable<ErrorCount>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertErrorCountsTemp")]
		public int InsertErrorCountsTemp()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllErrorCounts", IsComposable=true)]
		public IQueryable<GetAllErrorCountsResult> GetAllErrorCounts([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> datumOd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> datumDo)
		{
			return this.CreateMethodCallQuery<GetAllErrorCountsResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), datumOd, datumDo);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetErrorCountsGrouped", IsComposable=true)]
		public IQueryable<GetErrorCountsGroupedResult> GetErrorCountsGrouped([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> datumOd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> datumDo)
		{
			return this.CreateMethodCallQuery<GetErrorCountsGroupedResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), datumOd, datumDo);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SysLog")]
	public partial class SysLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MsgID;
		
		private int _EngineID;
		
		private System.DateTime _DateTime;
		
		private string _IP;
		
		private byte _Acknowledged;
		
		private byte _SysLogFacility;
		
		private byte _SysLogSeverity;
		
		private string _Hostname_ANSI;
		
		private string _Hostname_UNICODE;
		
		private long _NodeID;
		
		private string _MessageType_ANSI;
		
		private string _MessageType_UNICODE;
		
		private string _Message_ANSI;
		
		private string _Message_UNICODE;
		
		private string _SysLogTag_ANSI;
		
		private string _SysLogTag_UNICODE;
		
		private string _FirstIPInMessage;
		
		private string _SecIPInMessage;
		
		private string _MacInMessage;
		
		private System.Data.Linq.Binary _TimeStamp;
		
		private string _Hostname;
		
		private string _Message;
		
		private string _MessageType;
		
		private string _SysLogTag;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMsgIDChanging(long value);
    partial void OnMsgIDChanged();
    partial void OnEngineIDChanging(int value);
    partial void OnEngineIDChanged();
    partial void OnDateTimeChanging(System.DateTime value);
    partial void OnDateTimeChanged();
    partial void OnIPChanging(string value);
    partial void OnIPChanged();
    partial void OnAcknowledgedChanging(byte value);
    partial void OnAcknowledgedChanged();
    partial void OnSysLogFacilityChanging(byte value);
    partial void OnSysLogFacilityChanged();
    partial void OnSysLogSeverityChanging(byte value);
    partial void OnSysLogSeverityChanged();
    partial void OnHostname_ANSIChanging(string value);
    partial void OnHostname_ANSIChanged();
    partial void OnHostname_UNICODEChanging(string value);
    partial void OnHostname_UNICODEChanged();
    partial void OnNodeIDChanging(long value);
    partial void OnNodeIDChanged();
    partial void OnMessageType_ANSIChanging(string value);
    partial void OnMessageType_ANSIChanged();
    partial void OnMessageType_UNICODEChanging(string value);
    partial void OnMessageType_UNICODEChanged();
    partial void OnMessage_ANSIChanging(string value);
    partial void OnMessage_ANSIChanged();
    partial void OnMessage_UNICODEChanging(string value);
    partial void OnMessage_UNICODEChanged();
    partial void OnSysLogTag_ANSIChanging(string value);
    partial void OnSysLogTag_ANSIChanged();
    partial void OnSysLogTag_UNICODEChanging(string value);
    partial void OnSysLogTag_UNICODEChanged();
    partial void OnFirstIPInMessageChanging(string value);
    partial void OnFirstIPInMessageChanged();
    partial void OnSecIPInMessageChanging(string value);
    partial void OnSecIPInMessageChanged();
    partial void OnMacInMessageChanging(string value);
    partial void OnMacInMessageChanged();
    partial void OnTimeStampChanging(System.Data.Linq.Binary value);
    partial void OnTimeStampChanged();
    partial void OnHostnameChanging(string value);
    partial void OnHostnameChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnMessageTypeChanging(string value);
    partial void OnMessageTypeChanged();
    partial void OnSysLogTagChanging(string value);
    partial void OnSysLogTagChanged();
    #endregion
		
		public SysLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public long MsgID
		{
			get
			{
				return this._MsgID;
			}
			set
			{
				if ((this._MsgID != value))
				{
					this.OnMsgIDChanging(value);
					this.SendPropertyChanging();
					this._MsgID = value;
					this.SendPropertyChanged("MsgID");
					this.OnMsgIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EngineID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int EngineID
		{
			get
			{
				return this._EngineID;
			}
			set
			{
				if ((this._EngineID != value))
				{
					this.OnEngineIDChanging(value);
					this.SendPropertyChanging();
					this._EngineID = value;
					this.SendPropertyChanged("EngineID");
					this.OnEngineIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTime", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime DateTime
		{
			get
			{
				return this._DateTime;
			}
			set
			{
				if ((this._DateTime != value))
				{
					this.OnDateTimeChanging(value);
					this.SendPropertyChanging();
					this._DateTime = value;
					this.SendPropertyChanged("DateTime");
					this.OnDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string IP
		{
			get
			{
				return this._IP;
			}
			set
			{
				if ((this._IP != value))
				{
					this.OnIPChanging(value);
					this.SendPropertyChanging();
					this._IP = value;
					this.SendPropertyChanged("IP");
					this.OnIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Acknowledged", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte Acknowledged
		{
			get
			{
				return this._Acknowledged;
			}
			set
			{
				if ((this._Acknowledged != value))
				{
					this.OnAcknowledgedChanging(value);
					this.SendPropertyChanging();
					this._Acknowledged = value;
					this.SendPropertyChanged("Acknowledged");
					this.OnAcknowledgedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SysLogFacility", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte SysLogFacility
		{
			get
			{
				return this._SysLogFacility;
			}
			set
			{
				if ((this._SysLogFacility != value))
				{
					this.OnSysLogFacilityChanging(value);
					this.SendPropertyChanging();
					this._SysLogFacility = value;
					this.SendPropertyChanged("SysLogFacility");
					this.OnSysLogFacilityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SysLogSeverity", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte SysLogSeverity
		{
			get
			{
				return this._SysLogSeverity;
			}
			set
			{
				if ((this._SysLogSeverity != value))
				{
					this.OnSysLogSeverityChanging(value);
					this.SendPropertyChanging();
					this._SysLogSeverity = value;
					this.SendPropertyChanged("SysLogSeverity");
					this.OnSysLogSeverityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hostname_ANSI", DbType="VarChar(255) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Hostname_ANSI
		{
			get
			{
				return this._Hostname_ANSI;
			}
			set
			{
				if ((this._Hostname_ANSI != value))
				{
					this.OnHostname_ANSIChanging(value);
					this.SendPropertyChanging();
					this._Hostname_ANSI = value;
					this.SendPropertyChanged("Hostname_ANSI");
					this.OnHostname_ANSIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hostname_UNICODE", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string Hostname_UNICODE
		{
			get
			{
				return this._Hostname_UNICODE;
			}
			set
			{
				if ((this._Hostname_UNICODE != value))
				{
					this.OnHostname_UNICODEChanging(value);
					this.SendPropertyChanging();
					this._Hostname_UNICODE = value;
					this.SendPropertyChanged("Hostname_UNICODE");
					this.OnHostname_UNICODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeID", DbType="BigInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public long NodeID
		{
			get
			{
				return this._NodeID;
			}
			set
			{
				if ((this._NodeID != value))
				{
					this.OnNodeIDChanging(value);
					this.SendPropertyChanging();
					this._NodeID = value;
					this.SendPropertyChanged("NodeID");
					this.OnNodeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageType_ANSI", DbType="VarChar(100) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string MessageType_ANSI
		{
			get
			{
				return this._MessageType_ANSI;
			}
			set
			{
				if ((this._MessageType_ANSI != value))
				{
					this.OnMessageType_ANSIChanging(value);
					this.SendPropertyChanging();
					this._MessageType_ANSI = value;
					this.SendPropertyChanged("MessageType_ANSI");
					this.OnMessageType_ANSIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageType_UNICODE", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string MessageType_UNICODE
		{
			get
			{
				return this._MessageType_UNICODE;
			}
			set
			{
				if ((this._MessageType_UNICODE != value))
				{
					this.OnMessageType_UNICODEChanging(value);
					this.SendPropertyChanging();
					this._MessageType_UNICODE = value;
					this.SendPropertyChanged("MessageType_UNICODE");
					this.OnMessageType_UNICODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message_ANSI", DbType="VarChar(1024) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Message_ANSI
		{
			get
			{
				return this._Message_ANSI;
			}
			set
			{
				if ((this._Message_ANSI != value))
				{
					this.OnMessage_ANSIChanging(value);
					this.SendPropertyChanging();
					this._Message_ANSI = value;
					this.SendPropertyChanged("Message_ANSI");
					this.OnMessage_ANSIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message_UNICODE", DbType="NVarChar(1024)", UpdateCheck=UpdateCheck.Never)]
		public string Message_UNICODE
		{
			get
			{
				return this._Message_UNICODE;
			}
			set
			{
				if ((this._Message_UNICODE != value))
				{
					this.OnMessage_UNICODEChanging(value);
					this.SendPropertyChanging();
					this._Message_UNICODE = value;
					this.SendPropertyChanged("Message_UNICODE");
					this.OnMessage_UNICODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SysLogTag_ANSI", DbType="VarChar(100) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string SysLogTag_ANSI
		{
			get
			{
				return this._SysLogTag_ANSI;
			}
			set
			{
				if ((this._SysLogTag_ANSI != value))
				{
					this.OnSysLogTag_ANSIChanging(value);
					this.SendPropertyChanging();
					this._SysLogTag_ANSI = value;
					this.SendPropertyChanged("SysLogTag_ANSI");
					this.OnSysLogTag_ANSIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SysLogTag_UNICODE", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string SysLogTag_UNICODE
		{
			get
			{
				return this._SysLogTag_UNICODE;
			}
			set
			{
				if ((this._SysLogTag_UNICODE != value))
				{
					this.OnSysLogTag_UNICODEChanging(value);
					this.SendPropertyChanging();
					this._SysLogTag_UNICODE = value;
					this.SendPropertyChanged("SysLogTag_UNICODE");
					this.OnSysLogTag_UNICODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstIPInMessage", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string FirstIPInMessage
		{
			get
			{
				return this._FirstIPInMessage;
			}
			set
			{
				if ((this._FirstIPInMessage != value))
				{
					this.OnFirstIPInMessageChanging(value);
					this.SendPropertyChanging();
					this._FirstIPInMessage = value;
					this.SendPropertyChanged("FirstIPInMessage");
					this.OnFirstIPInMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecIPInMessage", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string SecIPInMessage
		{
			get
			{
				return this._SecIPInMessage;
			}
			set
			{
				if ((this._SecIPInMessage != value))
				{
					this.OnSecIPInMessageChanging(value);
					this.SendPropertyChanging();
					this._SecIPInMessage = value;
					this.SendPropertyChanged("SecIPInMessage");
					this.OnSecIPInMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MacInMessage", DbType="VarChar(12) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string MacInMessage
		{
			get
			{
				return this._MacInMessage;
			}
			set
			{
				if ((this._MacInMessage != value))
				{
					this.OnMacInMessageChanging(value);
					this.SendPropertyChanging();
					this._MacInMessage = value;
					this.SendPropertyChanged("MacInMessage");
					this.OnMacInMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeStamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary TimeStamp
		{
			get
			{
				return this._TimeStamp;
			}
			set
			{
				if ((this._TimeStamp != value))
				{
					this.OnTimeStampChanging(value);
					this.SendPropertyChanging();
					this._TimeStamp = value;
					this.SendPropertyChanged("TimeStamp");
					this.OnTimeStampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hostname", AutoSync=AutoSync.Always, DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string Hostname
		{
			get
			{
				return this._Hostname;
			}
			set
			{
				if ((this._Hostname != value))
				{
					this.OnHostnameChanging(value);
					this.SendPropertyChanging();
					this._Hostname = value;
					this.SendPropertyChanged("Hostname");
					this.OnHostnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", AutoSync=AutoSync.Always, DbType="NVarChar(1024) NOT NULL", CanBeNull=false, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageType", AutoSync=AutoSync.Always, DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string MessageType
		{
			get
			{
				return this._MessageType;
			}
			set
			{
				if ((this._MessageType != value))
				{
					this.OnMessageTypeChanging(value);
					this.SendPropertyChanging();
					this._MessageType = value;
					this.SendPropertyChanged("MessageType");
					this.OnMessageTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SysLogTag", AutoSync=AutoSync.Always, DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string SysLogTag
		{
			get
			{
				return this._SysLogTag;
			}
			set
			{
				if ((this._SysLogTag != value))
				{
					this.OnSysLogTagChanging(value);
					this.SendPropertyChanging();
					this._SysLogTag = value;
					this.SendPropertyChanged("SysLogTag");
					this.OnSysLogTagChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ErrorCounts")]
	public partial class ErrorCount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Interface;
		
		private System.Nullable<int> _NumberOfErrors;
		
		private string _Hostname;
		
		private string _IP;
		
		private System.Nullable<System.DateTime> _Datum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnInterfaceChanging(string value);
    partial void OnInterfaceChanged();
    partial void OnNumberOfErrorsChanging(System.Nullable<int> value);
    partial void OnNumberOfErrorsChanged();
    partial void OnHostnameChanging(string value);
    partial void OnHostnameChanged();
    partial void OnIPChanging(string value);
    partial void OnIPChanged();
    partial void OnDatumChanging(System.Nullable<System.DateTime> value);
    partial void OnDatumChanged();
    #endregion
		
		public ErrorCount()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Interface", DbType="VarChar(255)")]
		public string Interface
		{
			get
			{
				return this._Interface;
			}
			set
			{
				if ((this._Interface != value))
				{
					this.OnInterfaceChanging(value);
					this.SendPropertyChanging();
					this._Interface = value;
					this.SendPropertyChanged("Interface");
					this.OnInterfaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberOfErrors", DbType="Int")]
		public System.Nullable<int> NumberOfErrors
		{
			get
			{
				return this._NumberOfErrors;
			}
			set
			{
				if ((this._NumberOfErrors != value))
				{
					this.OnNumberOfErrorsChanging(value);
					this.SendPropertyChanging();
					this._NumberOfErrors = value;
					this.SendPropertyChanged("NumberOfErrors");
					this.OnNumberOfErrorsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hostname", DbType="NVarChar(255)")]
		public string Hostname
		{
			get
			{
				return this._Hostname;
			}
			set
			{
				if ((this._Hostname != value))
				{
					this.OnHostnameChanging(value);
					this.SendPropertyChanging();
					this._Hostname = value;
					this.SendPropertyChanged("Hostname");
					this.OnHostnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP", DbType="VarChar(50)")]
		public string IP
		{
			get
			{
				return this._IP;
			}
			set
			{
				if ((this._IP != value))
				{
					this.OnIPChanging(value);
					this.SendPropertyChanging();
					this._IP = value;
					this.SendPropertyChanged("IP");
					this.OnIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datum", DbType="Date")]
		public System.Nullable<System.DateTime> Datum
		{
			get
			{
				return this._Datum;
			}
			set
			{
				if ((this._Datum != value))
				{
					this.OnDatumChanging(value);
					this.SendPropertyChanging();
					this._Datum = value;
					this.SendPropertyChanged("Datum");
					this.OnDatumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetAllErrorCountsResult
	{
		
		private int _ID;
		
		private string _Interface;
		
		private System.Nullable<int> _NumberOfErrors;
		
		private string _Hostname;
		
		private string _IP;
		
		private System.Nullable<System.DateTime> _Datum;
		
		public GetAllErrorCountsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Interface", DbType="VarChar(255)")]
		public string Interface
		{
			get
			{
				return this._Interface;
			}
			set
			{
				if ((this._Interface != value))
				{
					this._Interface = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberOfErrors", DbType="Int")]
		public System.Nullable<int> NumberOfErrors
		{
			get
			{
				return this._NumberOfErrors;
			}
			set
			{
				if ((this._NumberOfErrors != value))
				{
					this._NumberOfErrors = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hostname", DbType="NVarChar(255)")]
		public string Hostname
		{
			get
			{
				return this._Hostname;
			}
			set
			{
				if ((this._Hostname != value))
				{
					this._Hostname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP", DbType="VarChar(50)")]
		public string IP
		{
			get
			{
				return this._IP;
			}
			set
			{
				if ((this._IP != value))
				{
					this._IP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datum", DbType="Date")]
		public System.Nullable<System.DateTime> Datum
		{
			get
			{
				return this._Datum;
			}
			set
			{
				if ((this._Datum != value))
				{
					this._Datum = value;
				}
			}
		}
	}
	
	public partial class GetErrorCountsGroupedResult
	{
		
		private string _Interface;
		
		private System.Nullable<int> _NumberOfErrors;
		
		private string _Hostname;
		
		private string _IP;
		
		private System.Nullable<System.DateTime> _Datum;
		
		public GetErrorCountsGroupedResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Interface", DbType="VarChar(255)")]
		public string Interface
		{
			get
			{
				return this._Interface;
			}
			set
			{
				if ((this._Interface != value))
				{
					this._Interface = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberOfErrors", DbType="Int")]
		public System.Nullable<int> NumberOfErrors
		{
			get
			{
				return this._NumberOfErrors;
			}
			set
			{
				if ((this._NumberOfErrors != value))
				{
					this._NumberOfErrors = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hostname", DbType="NVarChar(255)")]
		public string Hostname
		{
			get
			{
				return this._Hostname;
			}
			set
			{
				if ((this._Hostname != value))
				{
					this._Hostname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP", DbType="VarChar(50)")]
		public string IP
		{
			get
			{
				return this._IP;
			}
			set
			{
				if ((this._IP != value))
				{
					this._IP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datum", DbType="Date")]
		public System.Nullable<System.DateTime> Datum
		{
			get
			{
				return this._Datum;
			}
			set
			{
				if ((this._Datum != value))
				{
					this._Datum = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
